---
# Check that dependencies are installed
- name: Check dependencies
  import_tasks: dependencies.yml

# Import the templated config file
- name: Import configuration
  import_tasks: config.yml

# Prepare the firedancer environment
- name: Initialize firedancer hosts
  import_tasks: initialize.yml

# Run firedancer
- name: Run firedancer
  import_tasks: run.yml
