---
- name: Set solana keygen binary
  set_fact:
    labs_keygen: "{{ labs_workdir }}/solana-keygen"

- name: Create keys directory
  ansible.builtin.file:
    path: "{{ labs_keys_dir }}"
    state: directory

- name: Create mint and staking faucet
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o {{ labs_faucet }} > /dev/null"
  args:
    creates: "{{ faucet }}"

- name: Create mint and staking authority keys
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o {{ labs_authority }} > /dev/null"
  args:
    creates: "{{ authority }}"

- name: Create bootstrap validator id keys
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o '{{ labs_keys_dir }}/id.json' > '{{ labs_keys_dir }}/id.seed'"
  args:
    creates:
      - "{{ labs_keys_dir }}/id.json"
      - "{{ labs_keys_dir }}/id.seed"

- name: Create bootstrap validator vote keys
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o '{{ labs_keys_dir }}/vote.json' > '{{ labs_keys_dir }}/vote.seed'"
  args:
    creates:
      - "{{ labs_keys_dir }}/vote.json"
      - "{{ labs_keys_dir }}/vote.seed"

- name: Create bootstrap validator stake keys
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o '{{ labs_keys_dir }}/stake.json' > '{{ labs_keys_dir }}/stake.seed'"
  args:
    creates:
      - "{{ labs_keys_dir }}/stake.json"
      - "{{ labs_keys_dir }}/stake.seed"
