---
- name: Set solana keygen binary
  set_fact:
    labs_keygen: "{{ labs_workdir }}/solana-keygen"

- name: Create keys directory
  ansible.builtin.file:
    path: "{{ labs_keys_dir }}"
    state: directory

- name: Create mint and staking faucet
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o {{ labs_faucet }}"
  args:
    creates: "{{ labs_faucet }}"

- name: Create mint and staking authority keys
  command: "{{ labs_keygen }} new --no-bip39-passphrase -o {{ labs_authority }}"
  args:
    creates: "{{ labs_authority }}"

- name: Create bootstrap validator id keys
  shell: "{{ labs_keygen }} new --no-bip39-passphrase --force -o {{ labs_keys_dir }}/id.json > {{ labs_keys_dir }}/id.seed"
  args:
    creates:
      - "{{ labs_keys_dir }}/id.json"
      - "{{ labs_keys_dir }}/id.seed"

- name: Create bootstrap validator vote keys
  shell: "{{ labs_keygen }} new --no-bip39-passphrase --force -o {{ labs_keys_dir }}/vote.json > {{ labs_keys_dir }}/vote.seed"
  args:
    creates:
      - "{{ labs_keys_dir }}/vote.json"
      - "{{ labs_keys_dir }}/vote.seed"

- name: Create bootstrap validator stake keys
  shell: "{{ labs_keygen }} new --no-bip39-passphrase --force -o {{ labs_keys_dir }}/stake.json > {{ labs_keys_dir }}/stake.seed"
  args:
    creates:
      - "{{ labs_keys_dir }}/stake.json"
      - "{{ labs_keys_dir }}/stake.seed"
