---
- name: Set genesis host
  ansible.builtin.set_fact:
    genesis_host: "{{ groups['genesis'][0] }}"

- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Create validator keys
  ansible.builtin.import_tasks: keygen.yml
  when: override_keygen | default(false)

- name: Gather cluster facts
  ansible.builtin.import_tasks: gather.yml

- name: Run the bootstrap validator
  ansible.builtin.import_tasks: bootstrap.yml
  when: 
    - inventory_hostname == genesis_host
    - is_bootstrap | default(false)

- name: Run the join validator 
  ansible.builtin.import_tasks: join.yml
  when: 
    - inventory_hostname != genesis_host
    - is_join | default(false)
