---
- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Creating validator keys
  ansible.builtin.import_tasks: keygen.yml
  when: override_keygen | default(false)

- name: Run the bootstrap validator
  ansible.builtin.import_tasks: run.yml
