---
# TODO: sanity check host declarations
all:
  hosts:

  children:
    fd_build:
      hosts:

    labs_build:
      hosts:

    genesis:
      hosts:

    fd_run:
      hosts:

    labs_run:
      hosts:

    fd_hosts:
      children:
        fd_build:
        fd_run:

    labs_hosts:
      children:
        labs_build:
        labs_run:
